# Generated by Django 5.0.6 on 2024-08-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'ordering': ['name']},
        ),
    ]
